### ISSUE TITLE
makepkg is broken after commit c2b1c84

### ISSUE THREAD

**Issue by ivdimitro** [aarnt/octopi#392]
Hi, after the commit which added the Qt-AES classes the makepkg is not building octopi. Make is working but makepkg is not Failing with error: 
```
g++ -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o bin/octopi-repoeditor build/addrepo.o build/checkboxdelegate.o build/main.o build/optionsdelegate.o build/repoconf.o build/repoeditor.o build/repoentry.o build/unixcommand.o build/strconstants.o build/wmhelper.o build/terminal.o build/settingsmanager.o build/searchlineedit.o build/utils.o build/package.o build/qtsingleapplication.o build/qtlocalpeer.o build/qtsinglecoreapplication.o build/qrc_resources.o build/moc_addrepo.o build/moc_checkboxdelegate.o build/moc_optionsdelegate.o build/moc_repoconf.o build/moc_repoeditor.o build/moc_unixcommand.o build/moc_terminal.o build/moc_searchlineedit.o build/moc_qtsingleapplication.o build/moc_qtlocalpeer.o build/moc_qtsinglecoreapplication.o   /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Network.so /usr/lib/libQt5Xml.so /usr/lib/libQt5Core.so /usr/lib/libGL.so -lpthread
/usr/bin/ld: build/settingsmanager.o: in function `SettingsManager::getAURPassword()':
/home/power/projects/octopi/src/octopi/repoeditor/../src/settingsmanager.cpp:446: undefined reference to `QAESEncryption::QAESEncryption(QAESEncryption::Aes, QAESEncryption::Mode, QAESEncryption::Padding)'
/usr/bin/ld: /home/power/projects/octopi/src/octopi/repoeditor/../src/settingsmanager.cpp:447: undefined reference to `QAESEncryption::decode(QByteArray const&, QByteArray const&, QByteArray const&)'
/usr/bin/ld: /home/power/projects/octopi/src/octopi/repoeditor/../src/settingsmanager.cpp:448: undefined reference to `QAESEncryption::removePadding(QByteArray const&)'
/usr/bin/ld: build/settingsmanager.o: in function `QAESEncryption::~QAESEncryption()':
/home/power/projects/octopi/src/octopi/repoeditor/../src/qaesencryption.h:36: undefined reference to `vtable for QAESEncryption'
/usr/bin/ld: build/settingsmanager.o: in function `SettingsManager::setAURPassword(QString const&)':
/home/power/projects/octopi/src/octopi/repoeditor/../src/settingsmanager.cpp:750: undefined reference to `QAESEncryption::QAESEncryption(QAESEncryption::Aes, QAESEncryption::Mode, QAESEncryption::Padding)'
/usr/bin/ld: /home/power/projects/octopi/src/octopi/repoeditor/../src/settingsmanager.cpp:751: undefined reference to `QAESEncryption::encode(QByteArray const&, QByteArray const&, QByteArray const&)'
/usr/bin/ld: build/settingsmanager.o: in function `QAESEncryption::~QAESEncryption()':
/home/power/projects/octopi/src/octopi/repoeditor/../src/qaesencryption.h:36: undefined reference to `vtable for QAESEncryption'
/usr/bin/ld: /home/power/projects/octopi/src/octopi/repoeditor/../src/qaesencryption.h:36: undefined reference to `vtable for QAESEncryption'
/usr/bin/ld: /home/power/projects/octopi/src/octopi/repoeditor/../src/qaesencryption.h:36: undefined reference to `vtable for QAESEncryption'
collect2: error: ld returned 1 exit status
make: *** [Makefile:443: bin/octopi-repoeditor] Error 1
```
I have found out that the octopi-repoeditor.pro is missing the qaesencryption.h/cpp but adding them helps building the project in QT creator but not makepkg. 
I guess the issue is that makepkg is cloning the sources again and it is not applying the fix. 
I tried to fix it but I am not good enough with arch packaging yet to fix it. 
Could you take a look? 
Thanks.

**Comment by aarnt** [comment]
I'll take a look at it ASAP.
Thanks.

**Comment by aarnt** [comment]
Hi @ivdimitro ,
Can you test again?

**Comment by ivdimitro** [comment]
Makepkg -fi works again. Thanks.
